name: augur
channels:
- bioconda
- defaults
dependencies:
- python=3.6
- mafft
- raxml
- fasttree
- iqtree
- vcftools
- snakemake
- pip
- pip:
  - git+https://github.com/yilinxu/augur.git
  - biopython
  - pandas
