name: gen3-augur
channels:
- bioconda
- defaults
dependencies:
- python=3.6
- mafft
- raxml
- fasttree
- iqtree
- vcftools
- snakemake
- pip
- pip:
  - git+https://github.com/uc-cdis/augur.git
  - biopython
  - pandas
  - pandas
  - requests
